INSERT INTO genres(id, name) VALUES
(nextval('base_sequence'), 'nu metal'),
(nextval('base_sequence'), 'melodic death metal'),
(nextval('base_sequence'), 'deathcore'),
(nextval('base_sequence'), 'alternative rock'),
(nextval('base_sequence'), 'progressive metal'),
(nextval('base_sequence'), 'metalcore'),
(nextval('base_sequence'), 'punk rock'),
(nextval('base_sequence'), 'grunge'),
(nextval('base_sequence'), 'post-grunge'),
(nextval('base_sequence'), 'post-rock'),
(nextval('base_sequence'), 'big beat'),
(nextval('base_sequence'), 'drum''n''base'),
(nextval('base_sequence'), 'trance'),
(nextval('base_sequence'), 'ambient');

INSERT INTO music_groups(id, name, year_creation, year_decay) VALUES
(nextval('base_sequence'), 'Slipknot', 1992, null),
(nextval('base_sequence'), 'System Of a Down', 1992, null),
(nextval('base_sequence'), 'Papa Roach', 1993, null),
(nextval('base_sequence'), 'Arch Enemy', 1996, null),
(nextval('base_sequence'), 'In Flames', 1996, null),
(nextval('base_sequence'), 'Suicide Silence', 2002, null),
(nextval('base_sequence'), 'Animals As Leaders', 2007, null),
(nextval('base_sequence'), 'Bullet For My Valentine', 2003, null),
(nextval('base_sequence'), 'Asking Alexandria', 2008, null),
(nextval('base_sequence'), 'I Prevail', 2013, null),
(nextval('base_sequence'), 'Rise Against', 1999, null),
(nextval('base_sequence'), 'Yellowcard', 1997, 2017),
(nextval('base_sequence'), 'Nirvana', 1987, 1994),
(nextval('base_sequence'), 'Three Days Grace', 1997, null),
(nextval('base_sequence'), 'Shinedown', 2001, null),
(nextval('base_sequence'), 'This Will Destroy You', 2004, null),
(nextval('base_sequence'), 'The Prodigy', 1990, 2019),
(nextval('base_sequence'), 'The Chemical Brothers', 1989, null),
(nextval('base_sequence'), 'Pendulum', 2002, null),
(nextval('base_sequence'), 'Armin van Buuren', 1996, null),
(nextval('base_sequence'), 'Jean-Michel Jarre', 1969, null);

INSERT INTO albums(id, name, year_release, music_group_id, genre_id) VALUES
(nextval('base_sequence'), 'Iowa', 2001, (SELECT id FROM music_groups WHERE name = 'Slipknot'), (SELECT id FROM genres WHERE name = 'nu metal')),
(nextval('base_sequence'), 'We Are Not Your Kind', 2019, (SELECT id FROM music_groups WHERE name = 'Slipknot'), (SELECT id FROM genres WHERE name = 'nu metal')),
(nextval('base_sequence'), 'Toxicity', 2001, (SELECT id FROM music_groups WHERE name = 'System Of a Down'), (SELECT id FROM genres WHERE name = 'nu metal')),
(nextval('base_sequence'), 'Infest', 2000, (SELECT id FROM music_groups WHERE name = 'Papa Roach'), (SELECT id FROM genres WHERE name = 'nu metal')),
(nextval('base_sequence'), 'Lovehatetragedy', 2002, (SELECT id FROM music_groups WHERE name = 'Papa Roach'), (SELECT id FROM genres WHERE name = 'nu metal')),
(nextval('base_sequence'), 'Getting Away with Murder', 2004, (SELECT id FROM music_groups WHERE name = 'Papa Roach'), (SELECT id FROM genres WHERE name = 'alternative rock')),
(nextval('base_sequence'), 'Wages of Sin', 2002, (SELECT id FROM music_groups WHERE name = 'Arch Enemy'), (SELECT id FROM genres WHERE name = 'melodic death metal')),
(nextval('base_sequence'), 'Soundtrack to Your Escape', 2004, (SELECT id FROM music_groups WHERE name = 'In Flames'), (SELECT id FROM genres WHERE name = 'melodic death metal')),
(nextval('base_sequence'), 'No Time to Bleed', 2009, (SELECT id FROM music_groups WHERE name = 'Suicide Silence'), (SELECT id FROM genres WHERE name = 'deathcore')),
(nextval('base_sequence'), 'The Black Crown', 2011, (SELECT id FROM music_groups WHERE name = 'Suicide Silence'), (SELECT id FROM genres WHERE name = 'deathcore')),
(nextval('base_sequence'), 'Animals As Leaders', 2009, (SELECT id FROM music_groups WHERE name = 'Animals As Leaders'), (SELECT id FROM genres WHERE name = 'progressive metal')),
(nextval('base_sequence'), 'Weightless', 2011, (SELECT id FROM music_groups WHERE name = 'Animals As Leaders'), (SELECT id FROM genres WHERE name = 'progressive metal')),
(nextval('base_sequence'), 'The Joy of Motion', 2014, (SELECT id FROM music_groups WHERE name = 'Animals As Leaders'), (SELECT id FROM genres WHERE name = 'progressive metal')),
(nextval('base_sequence'), 'The Madness of Many', 2016, (SELECT id FROM music_groups WHERE name = 'Animals As Leaders'), (SELECT id FROM genres WHERE name = 'progressive metal')),
(nextval('base_sequence'), 'The Poison', 2005, (SELECT id FROM music_groups WHERE name = 'Bullet For My Valentine'), (SELECT id FROM genres WHERE name = 'metalcore')),
(nextval('base_sequence'), 'Fever', 2010, (SELECT id FROM music_groups WHERE name = 'Bullet For My Valentine'), (SELECT id FROM genres WHERE name = 'metalcore')),
(nextval('base_sequence'), 'Gravity', 2018, (SELECT id FROM music_groups WHERE name = 'Bullet For My Valentine'), (SELECT id FROM genres WHERE name = 'metalcore')),
(nextval('base_sequence'), 'Stand Up and Scream', 2009, (SELECT id FROM music_groups WHERE name = 'Asking Alexandria'), (SELECT id FROM genres WHERE name = 'metalcore')),
(nextval('base_sequence'), 'Like a House on Fire', 2020, (SELECT id FROM music_groups WHERE name = 'Asking Alexandria'), (SELECT id FROM genres WHERE name = 'alternative rock')),
(nextval('base_sequence'), 'Lifelines', 2016, (SELECT id FROM music_groups WHERE name = 'I Prevail'), (SELECT id FROM genres WHERE name = 'metalcore')),
(nextval('base_sequence'), 'Trauma', 2019, (SELECT id FROM music_groups WHERE name = 'I Prevail'), (SELECT id FROM genres WHERE name = 'metalcore')),
(nextval('base_sequence'), 'Appeal to Reason', 2008, (SELECT id FROM music_groups WHERE name = 'Rise Against'), (SELECT id FROM genres WHERE name = 'punk rock')),
(nextval('base_sequence'), 'The Black Market', 2014, (SELECT id FROM music_groups WHERE name = 'Rise Against'), (SELECT id FROM genres WHERE name = 'punk rock')),
(nextval('base_sequence'), 'Ocean Avenue', 2003, (SELECT id FROM music_groups WHERE name = 'Yellowcard'), (SELECT id FROM genres WHERE name = 'punk rock')),
(nextval('base_sequence'), 'Paper Walls', 2007, (SELECT id FROM music_groups WHERE name = 'Yellowcard'), (SELECT id FROM genres WHERE name = 'punk rock')),
(nextval('base_sequence'), 'Bleach', 1989, (SELECT id FROM music_groups WHERE name = 'Nirvana'), (SELECT id FROM genres WHERE name = 'grunge')),
(nextval('base_sequence'), 'Nevermind', 1991, (SELECT id FROM music_groups WHERE name = 'Nirvana'), (SELECT id FROM genres WHERE name = 'grunge')),
(nextval('base_sequence'), 'In Utero', 1993, (SELECT id FROM music_groups WHERE name = 'Nirvana'), (SELECT id FROM genres WHERE name = 'grunge')),
(nextval('base_sequence'), 'Three Days Grace', 2003, (SELECT id FROM music_groups WHERE name = 'Three Days Grace'), (SELECT id FROM genres WHERE name = 'post-grunge')),
(nextval('base_sequence'), 'Outsider', 2018, (SELECT id FROM music_groups WHERE name = 'Three Days Grace'), (SELECT id FROM genres WHERE name = 'post-grunge')),
(nextval('base_sequence'), 'The Sound of Madness', 2008, (SELECT id FROM music_groups WHERE name = 'Shinedown'), (SELECT id FROM genres WHERE name = 'post-grunge')),
(nextval('base_sequence'), 'Attention Attention', 2018, (SELECT id FROM music_groups WHERE name = 'Shinedown'), (SELECT id FROM genres WHERE name = 'post-grunge')),
(nextval('base_sequence'), 'Young Mountain', 2006, (SELECT id FROM music_groups WHERE name = 'This Will Destroy You'), (SELECT id FROM genres WHERE name = 'post-rock')),
(nextval('base_sequence'), 'Another Language', 2014, (SELECT id FROM music_groups WHERE name = 'This Will Destroy You'), (SELECT id FROM genres WHERE name = 'post-rock')),
(nextval('base_sequence'), 'Music for the Jilted Generation', 1994, (SELECT id FROM music_groups WHERE name = 'The Prodigy'), (SELECT id FROM genres WHERE name = 'big beat')),
(nextval('base_sequence'), 'The Fat of the Land', 1997, (SELECT id FROM music_groups WHERE name = 'The Prodigy'), (SELECT id FROM genres WHERE name = 'big beat')),
(nextval('base_sequence'), 'No Tourists', 2018, (SELECT id FROM music_groups WHERE name = 'The Prodigy'), (SELECT id FROM genres WHERE name = 'big beat')),
(nextval('base_sequence'), 'Push the Button', 2005, (SELECT id FROM music_groups WHERE name = 'The Chemical Brothers'), (SELECT id FROM genres WHERE name = 'big beat')),
(nextval('base_sequence'), 'Hold Your Colour', 2005, (SELECT id FROM music_groups WHERE name = 'Pendulum'), (SELECT id FROM genres WHERE name = 'drum''n''base')),
(nextval('base_sequence'), 'In Silico', 2008, (SELECT id FROM music_groups WHERE name = 'Pendulum'), (SELECT id FROM genres WHERE name = 'drum''n''base')),
(nextval('base_sequence'), 'Immersion', 2010, (SELECT id FROM music_groups WHERE name = 'Pendulum'), (SELECT id FROM genres WHERE name = 'drum''n''base')),
(nextval('base_sequence'), 'Imagine', 2008, (SELECT id FROM music_groups WHERE name = 'Armin van Buuren'), (SELECT id FROM genres WHERE name = 'trance')),
(nextval('base_sequence'), 'Embrace', 2015, (SELECT id FROM music_groups WHERE name = 'Armin van Buuren'), (SELECT id FROM genres WHERE name = 'trance')),
(nextval('base_sequence'), 'Oxygène', 1976, (SELECT id FROM music_groups WHERE name = 'Jean-Michel Jarre'), (SELECT id FROM genres WHERE name = 'ambient')),
(nextval('base_sequence'), 'Équinoxe', 1978, (SELECT id FROM music_groups WHERE name = 'Jean-Michel Jarre'), (SELECT id FROM genres WHERE name = 'ambient'));
